In [1]:
from imdb.caltech_imdb import caltech_imdb

In [3]:
imdb = caltech_imdb('train', './data')

In [4]:
index = imdb.image_index

In [5]:
##print index 

In [6]:
path = imdb.image_path_from_index(index[22])
print path

./data/Images/set00_V000_0022.jpg


In [7]:
roidb = imdb.gt_roidb()

[INFO - imdb]: train gt roidb loaded from ./train_gt_roidb.pkl


In [8]:
type(roidb)

list

In [9]:
ind = 100

In [10]:
roidb[220]

{'boxes': array([[422, 172, 438, 207],
        [451, 174, 466, 202],
        [517, 175, 530, 195],
        [496, 176, 511, 210],
        [216, 115, 225, 132]], dtype=uint16),
 'flipped': False,
 'gt_classes': array([1, 1, 1, 1, 1], dtype=int32),
 'gt_overlaps': <5x2 sparse matrix of type '<type 'numpy.float32'>'
 	with 5 stored elements in Compressed Sparse Row format>}

In [11]:
import cv2
import matplotlib.pyplot as plt

ind = 223
image = cv2.imread(imdb.image_path_from_index(index[ind]))

plt.imshow(image)
plt.show()

In [12]:
cv2.destroyAllWindows()

In [13]:
roidb[ind]

{'boxes': array([[426, 170, 442, 205],
        [453, 173, 468, 202],
        [523, 173, 535, 194],
        [501, 175, 516, 209],
        [216, 113, 225, 131]], dtype=uint16),
 'flipped': False,
 'gt_classes': array([1, 1, 1, 1, 1], dtype=int32),
 'gt_overlaps': <5x2 sparse matrix of type '<type 'numpy.float32'>'
 	with 5 stored elements in Compressed Sparse Row format>}

In [14]:
box = roidb[ind]['boxes']

In [15]:
print box

[[426 170 442 205]
 [453 173 468 202]
 [523 173 535 194]
 [501 175 516 209]
 [216 113 225 131]]


In [16]:
for b in box:
    cv2.rectangle(image, (b[0], b[1]), (b[2], b[3]), (0,0,255), 1)

plt.imshow(image)

In [17]:
plt.show()